### ISSUE TITLE
Add comments to input statements and document debts in tickets

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#1002]
- [x] Use IF-statement instead of fudge-factor
- [x] Get values from nodes instead of hard-coded values
- [ ] Take different range of insulation of old and new houses into account

**Comment by RobTerwel** [comment]
- [ ] HHP IF statement instead of Fudge factor #1008 
 - [ ] HHP Values from nodes instead of hard-coded ones #1009 
 - [ ] HHP Different mapping range of insulation of old and new houses #1010

**Comment by michieldenhaan** [comment]
Closing, issue seems to be outdated with recent heating/housing stock changes
