### ISSUE TITLE
OVERVIEW TICKET: CHP cleanup II

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etsource#890]
This ticket provides an overview of improvements of CHP modeling that are grouped under the "CHP cleanup II" milestone.

The background of the improvements is the impact of the current implementation has on profitability of power plants and Merit behavior. In particular:
- [x] https://github.com/quintel/etengine/issues/706. Must-run CHPs should be available for electricity production with the remainder of their capacity (the part that is not must-run). Currently, the behavior of must-run CHPs in the ETM is completely dominated by their profile. If the profile dictates that they are not running at a given hour, they will indeed not produce electrcitiy even if they could earn money by doing so. In reality, must-run CHPs will also participate in the merit-order at any time.
- [x] https://github.com/quintel/etsource/issues/236. Central (dispatchable) CHPs produce both heat and electricity. Their marginal cost includes the fuel for both products but in the merit-order the CHPs need to compete with plants that only produce electricity and, therefore, have lower marginal cost. In reality, the central CHPs would be compensated for the fuel they use to produce heat but this is not yet the case in the ETM.
- [x] https://github.com/quintel/etsource/issues/887. In order for https://github.com/quintel/etsource/issues/236 to work properly, we need to distinguish between central and de-central CHPs because they show different behavior when it comes to compensation for produced heat.

**Comment by michieldenhaan** [comment]
Closing, all underlying issues closed
